### ISSUE TITLE
For another editor

### ISSUE THREAD

**Issue by Alexey-T** [predragnikolic/sublime-git-diff-view#2]
Thanks for plugin. Maybe you can make version for CudaText too?

**Comment by predragnikolic** [comment]
Glad you like it, Alexey.
I can see that you are really passionate about the editor you are building! 

But to be honest with you, I don't see the excitement in building the same thing for another editor. At least not for now and I hope you will understand me :)

I build plugins for Sublime because I really like it and it is a great development tool.

**Comment by Alexey-T** [comment]
Thanks
